language: node_js
script: npm test
node_js:
  - node
  - '4'
  - '0.12'
notifications:
  email: false
deploy:
  provider: npm
  email: npm@eli-white.com
  api_key:
    secure: Y0OXEGraQ8Vbn0hv70gNu1DYUbp+2DxyzODVc49ntqTsIkzbPpXOctOJ8bS+qcOEiyWmrYxeNb4fePk2pTa+VXNJyG8RSz5D1Fsn6lxmJ92etbPG1dg4DhmQNcV/rRuq/7e0Xj0XsxG7QdCEvCmxuq+MJKEFeqgYPPP5ByxRBHQZTAZ1ULbNcdPAJbmdSIiV6o2Hc2fDRR0AoNU+IzYWMsW/iFIEiR3y2BZSlSaLTDe9kHAyIxRSNld4gdwDi+/4YPdkRbSvbfrF6L4R38xGy8egfCgiu/1prpZ6IGQoQBuIi4zlEi8/iAHNqwQghPGQFhiLDooIKB2/TFqb5CPlMj4QgN7Xy/M64jthS/gGVWdN00+9U89NT+3CPeQ+cKyXoFdipr44N0CTz2iG4qPd+R/SGKJG3ir0lwZ6vCWE9GTtRqx6+TVa9neZtjqSpmd0UReFTyiab8r6rF3CgZ8TV31ZmEHxCJ7feRqc5FEtD49XHFZku9bHUQxo234FtT9AZxgwHqkxFq5tpdcPHP8jvQirVoxgeAA8/j+JBz9w+ZOfIRB3PMJFr7GQ3Uh5+ZG1weh68COQisZU//0xKsaIvmC6dVs0KSoItUh9tX5Rys1yD0AR6fufCIxsKEh87e0hWz3FV9SRIBa343jeXhPrjxM30fjimcZYS98HufljhXU=
  on:
    tags: true
    repo: TheSavior/rewire-global
    node: '0.12'
