language: node_js
script: npm test
node_js:
- node
- io.js
- '0.12'
notifications:
  email: false
deploy:
  provider: npm
  email: npm@eli-white.com
  api_key:
    secure: yXoTwCdRoZ/CTI9//VGtELWQnQmhp0ICA1qJdxlFq1vHO7uUIBkVQqz6plivxlMTWm7w/De5Ft8hOq3KXFAfa8aDzdm1gS//oa9+7NFYZ1iqK74K3nxwPpdYjbGZyzjonnbEb95m6dbSZ31ZLjOs+W6a+LSGryYAViKjE3Flk+RpYaG/4+0hBf4HxLRJy6Ej5g5JiFS3eksmGrtGHTzi5dcN0sekSdObYu/RBxk4jhojy3NSWatfTGRxhj8Pc6e1dZUjCDL3wfZO81yWC3z2IUjkpvBfsJMnPQWVgl7SeLoJ216oc0NjZh17OCku4OPqHM7oEPJRjRZOi8L1WOmGUceCY3/lS09ClQm+w0KhwTQjO5KyBuNDHGm/2FuuAFb2f/k9fp+SU+rx77wrrjo57+JaxndYg3TCBj9EN1U+cN3Y7JqjMzxALo1FR8IsqlBVr4akPebENqehaOkLlrvWVY7ujVqFfbZrjbOOadlvzCAkws/O1p77W3YSrQgpNLwEbwTF3vlfSsR4y83VYItlxyN5PSxIsxve/ayQ36IJ0EffQ+NyogS8EMLpNJlzeQXdH+NPnKOHeebbSWPvm7FEL1gpADRNLbDjH7/OeUD/RGiniN1O7nP6ZVWld9qW8WooGagF0KSc/cHHrlM5qeCdH5E3UV3wtvBUcqs1eenyfRA=
  on:
    tags: true
    repo: TheSavior/rewire-global
    node: '0.12'
